stages:
  - build
  - analyze
  - pre-deploy-int
  - deploy-int
  - tag-image-prod
  - pre-deploy-prod
  - deploy-prod
variables:
  #  Configuration spécifique projet
  PROJECT_NAME:
    value: datawarehouse
    description: "Nom du projet à déployer"
  PROJECT_VERSION:
    value: "1.0"
    description: "Version du projet à déployer"
  SERVER_ENV_INT:
    value: "int-monitorfish-datawarehouse01"
    description: "Serveur cible d'intégration"
  SERVER_ENV_PROD:
    value: "prod-monitorfish-datawarehouse01"
    description: "Serveur cible de production"
  PROXY_HOST: "172.27.229.197"
  PROXY_PORT: "8090"
  TAG_VERSION: $NEXUS_DOCKER_REPO/$PROJECT_NAME:$PROJECT_VERSION

  #Anlayse Trivy
  FAIL_TRIVY_CONDITION:
    value: "--severity CRITICAL"
    description: "Détermine la commande à passer à Trivy pour bloquer ou non le job. --severity CRITICAL fait échouer le job si Trivy remonte des anomalies critiques."

  #Analyse Sonar
  FAIL_SONAR_CONDITION:
    value: "-Dsonar.qualitygate.wait=true"
    description: "Détermine la commande à passer au scanner Sonar pour bloquer ou non le job. -Dsonar.qualitygate.wait=true fait échouer le job si le quality gate Sonar n'est pas conforme."


include:
  - "/jobs-build-CI/construction_image.yml"
  - project: 'num3-exploitation/chaine-ci/template-analyse-deploiement'
    ref: main
    file: '/jobs/analyse_trivy.yml'
  - project: 'num3-exploitation/chaine-ci/template-analyse-deploiement'
    ref: main
    file: '/jobs/analyse_sonar.yml'
  # - "/jobs-build-CI/analyse_dependency-check.yml"
  # - project: 'num3-exploitation/chaine-ci/template-analyse-deploiement'
  #   ref: main
  #   file: '/jobs/deploiement_image_int.yml'
  # - project: 'num3-exploitation/chaine-ci/template-analyse-deploiement'
  #   ref: main
  #   file: '/jobs/deploiement_image_prod.yml'

