services:

  db:
    network_mode : host

  monitorfish-db:
    image: ghcr.io/mtes-mct/monitorfish/monitorfish-database:pg16-ts2.14.2-postgis3.5.1
    container_name: monitorfish_database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=monitorfish_test_db
    volumes:
      - monitorfish-db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 1s
      retries: 30

  monitorenv-db:
    image: ghcr.io/mtes-mct/monitorenv/monitorenv-database:pg11-ts1.7.4-postgis3.3.2
    container_name: monitorenv_database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=monitorenv_test_db
    volumes:
      - monitorenv-db-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 1s
      retries: 30


  monitorfish-flyway:
    image: flyway/flyway
    container_name: monitorfish_flyway
    command: migrate -password=postgres -schemas=public -user=postgres -url=jdbc:postgresql://monitorfish-db:5432/monitorfish_test_db
    volumes:
      - ../../forklift/tests/test_data/external/monitorfish/backend/src/main/resources/db/migration:/flyway/sql/schema
      - ../../forklift/tests/test_data/external/monitorfish/datascience/tests/test_data/remote_database/:/flyway/sql/test_data
    depends_on:
      monitorfish-db:
        condition: service_healthy

  monitorenv-flyway:
    image: flyway/flyway
    container_name: monitorenv_flyway
    command: migrate -password=postgres -schemas=public -user=postgres -url=jdbc:postgresql://monitorenv-db:5432/monitorenv_test_db
    volumes:
      - ../../forklift/tests/test_data/external/monitorenv/backend/src/main/resources/db/migration:/flyway/sql/schema
      - ../../forklift/tests/test_data/external/monitorenv/datascience/tests/test_data/remote_database/:/flyway/sql/test_data
      - ../../forklift/tests/test_data/monitorenv/remote_database/:/flyway/sql/extra_test_data
    depends_on:
      monitorenv-db:
        condition: service_healthy

volumes:
  monitorfish-db-data:
    driver: local
  monitorenv-db-data:
    driver: local
