---
project_name: "{{ lookup('env', 'PROJECT_NAME') }}"
docker_image_path: "{{ lookup('env', 'TAG_VERSION') }}"
docker_compose_path: "/opt/dockers/{{ project_name }}"
project_ports: "{{ lookup('env', 'PROJECT_PORTS') }}"
project_volumes: "{{ lookup('env', 'PROJECT_VOLUMES') }}"
nexus_user: "{{ lookup('env', 'NEXUS_USER') }}"
nexus_password: "{{ lookup('env', 'NEXUS_PWD') }}"
nexus_proxy: "{{ lookup('env', 'NEXUS_DOCKER_PROXY') }}"
