---
docker_image_path: "{{ lookup('env', 'TAG_VERSION') }}"
docker_compose_path: "/opt/dockers/{{ project_name }}"
nexus_repo: "{{ lookup('env', 'NEXUS_DOCKER_REPO') }}"
nexus_user: "{{ lookup('env', 'NEXUS_USER') }}"
nexus_password: "{{ lookup('env', 'NEXUS_PWD') }}"
version_application: "{{ lookup('env', 'PROJECT_VERSION') }}"
http_proxy: "{{ lookup('env', 'PROXY_HOST') }}"
port_proxy: "{{ lookup('env', 'PROXY_PORT') }}"
postgresql_port: "{{ lookup('env', 'POSTGRES_PORT') }}"

####################MONITORFISH_REMOTE########################
prod_monitorfish_remote_pwd : "{{ lookup('env', 'PROD_MONITORFISH_REMOTE_PWD') }}"
prod_monitorfish_remote_ip: "{{ lookup('env', 'PROD_MONITORFISH_REMOTE_IP') }}"
int_monitorfish_remote_pwd : "{{ lookup('env', 'INT_MONITORFISH_REMOTE_PWD') }}"
int_monitorfish_remote_ip: "{{ lookup('env', 'INT_MONITORFISH_REMOTE_IP') }}"
monitorfish_remote_db: "{{ lookup('env', 'MONITORFISH_REMOTE_DB') }}"
monitorfish_remote_user: "{{ lookup('env', 'POSTGRES_USER') }}"

###################MONITORENV_REMOTE#########################
prod_monitorenv_remote_pwd: "{{ lookup('env', 'PROD_MONITORENV_REMOTE_PWD') }}"
prod_monitorenv_remote_ip: "{{ lookup('env', 'PROD_MONITORENV_REMOTE_IP') }}"
int_monitorenv_remote_pwd: "{{ lookup('env', 'INT_MONITORENV_REMOTE_PWD') }}"
int_monitorenv_remote_ip: "{{ lookup('env', 'INT_MONITORENV_REMOTE_IP') }}"
monitorenv_remote_db: "{{ lookup('env', 'MONITORENV_REMOTE_DB') }}"
monitorenv_remote_user: "{{ lookup('env', 'POSTGRES_USER') }}"

###################MONITORFISH_LOCAL#########################
monitorfish_local_ip: "{{ lookup('env', 'IP_CROSS') }}"
monitorfish_local_name: "{{ lookup('env', 'MONITORFISH_LOCAL_NAME') }}"
monitorfish_local_user: "{{ lookup('env', 'USER_CROSS') }}"
monitorfish_local_pwd: "{{ lookup('env', 'MONITORFISH_LOCAL_PWD') }}"

###################CACEM_LOCAL###############################
cacem_local_ip: "{{ lookup('env', 'IP_CROSS') }}"
cacem_local_name: "{{ lookup('env', 'CACEM_LOCAL_NAME') }}"
cacem_local_user: "{{ lookup('env', 'USER_CROSS') }}"
cacem_local_pwd: "{{ lookup('env', 'MONITORFISH_LOCAL_PWD') }}"

####################DATA_WAREHOUSE###########################
prod_data_warehouse_ip: "{{ lookup('env', 'DATA_WAREHOUSE_IP_PROD') }}"
int_data_warehouse_ip: "{{ lookup('env', 'DATA_WAREHOUSE_IP_INT') }}"
data_warehouse_port: "{{ lookup('env', 'DATA_WAREHOUSE_PORT') }}"
data_warehouse_user: "{{ lookup('env', 'DATA_WAREHOUSE_USER') }}"
prod_data_warehouse_pwd: "{{ lookup('env', 'DATA_WAREHOUSE_PWD_PROD') }}"
int_data_warehouse_pwd: "{{ lookup('env', 'DATA_WAREHOUSE_PWD_INT') }}"

###########################API_KEY###########################
api_key_datagouv: "{{ lookup('env', 'DATAGOUV_API_KEY') }}"