---
docker_image_path: "{{ lookup('env', 'TAG_VERSION') }}"
docker_compose_path: "/opt/dockers/{{ project_name }}"
nexus_repo: "{{ lookup('env', 'NEXUS_DOCKER_REPO') }}"
nexus_user: "{{ lookup('env', 'NEXUS_USER') }}"
nexus_password: "{{ lookup('env', 'NEXUS_PWD') }}"
version_application: "{{ lookup('env', 'PROJECT_VERSION') }}"
path_file: "{{ '/home/d_dawar' if env==int else '/opt/docker/datawarehouse' }}"