version: '3'
services:
  db:
    image: clickhouse/clickhouse-server:23.11.4.24
    container_name: data_warehouse
    environment:
      - CLICKHOUSE_USER=$DATA_WAREHOUSE_USER
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1 
      - CLICKHOUSE_PASSWORD=$DATA_WAREHOUSE_PASSWORD
    volumes:
      - data-warehouse-db:/var/lib/clickhouse/
      - data-warehouse-logs:/var/log/clickhouse-server/
    ports:
      - 8123:8123
      - 9000:9000
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "wget http://localhost:8123/ping || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30

volumes:
  data-warehouse-db:
    driver: local
  data-warehouse-logs:
    driver: local
