---

# Création du docker-compose.yml et démarrage des containers

- name: "Log into nexus repository"
  command: docker login {{ nexus_docker }} -u {{ nexus_user }} -p {{ nexus_password }}
  no_log: true

- name: "Start docker-compose"
  command: source .data-warehouse && make register-forklift-flows

- name: "Log out of any docker registry"
  command: docker logout {{ nexus_docker }}
  no_log: true

