---

# Création du docker-compose.yml et démarrage des containers

- name: "Log into nexus repository"
  command: docker login {{ nexus_docker }} -u {{ nexus_user }} -p {{ nexus_password }}
  no_log: true

- name: "Debug - print docker and docker compose version"
  command: docker --version && docker compose version

- name: "Start docker-compose"
  become_user: d_dawar
  shell: source .data-warehouse && make run-datawarehouse && make register-forklift-flows
  args:
    chdir: "/home/d_dawar"
    executable: /bin/bash
  when: env == "int"

- name: "Start docker-compose"
  become_user: d_dawar
  shell: source .data-warehouse && make run-datawarehouse && make register-forklift-flows
  args:
    executable: /bin/bash
    chdir: "/opt/docker/datawarehouse"
  when: env == "prod"

- name: "Log out of any docker registry"
  command: docker logout {{ nexus_docker }}
  no_log: true

