---

# Création du docker-compose.yml et démarrage des containers

- name: "Log into nexus repository"
  command: docker login {{ nexus_docker }} -u {{ nexus_user }} -p {{ nexus_password }}
  no_log: true


- name: Capture docker information
  shell: docker --version
  register: docker_version

- name: Capture docker compose information
  shell: docker compose version
  register: docker_compose_version

- name: Print docker information
  debug:
    var: docker_version.stdout

- name: Print docker compose information
  debug:
    var: docker_compose_version.stdout

- name: "Start docker-compose"
  become_user: d_dawar
  shell: source .data-warehouse && make run-datawarehouse && make register-forklift-flows
  args:
    chdir: "/home/d_dawar"
    executable: /bin/bash
  when: env == "int"

- name: "Start docker-compose"
  become_user: d_dawar
  shell: source .data-warehouse && make run-datawarehouse && make register-forklift-flows
  args:
    executable: /bin/bash
    chdir: "/opt/docker/datawarehouse"
  when: env == "prod"

- name: "Log out of any docker registry"
  command: docker logout {{ nexus_docker }}
  no_log: true

