---
#------------------------------------------------------------------------
#   Liste des taches d'installation/mise à jour d'une image Docker
#------------------------------------------------------------------------

# Connexion au repository Nexus/récupération de l'image/logout
- name: "Log into nexus repository"
  command: docker login {{ nexus_repo }} -u {{ nexus_user }} -p {{ nexus_password }}
  no_log: true

- name: "Log out of any docker registry"
  command: docker logout {{ nexus_repo }}
  no_log: true

# Déploiement des fichiers de configuration de l'application
- name: "Copy infra/deploiement"
  copy:
    src: ../infra/deployment/docker-compose.yml
    dest: "{{ path_file }}/docker-compose.yml"
    mode: 0755

- name: "Creating new .env file"
  template:
    src: "../.gitlab-ci/templates/{{ env }}.env.j2"
    dest: "{{ path_file }}/.env"

- name: "Creating new .env file"
  template:
    src: "../.gitlab-ci/templates/.data-warehouse.j2"
    dest: "{{ path_file }}/.data-warehouse"

- name: "Pull docker images"
  command: "docker pull {{ docker_image_path }}"
  args:
    chdir: "{{ path_file }}"