---
#------------------------------------------------------------------------
#   Liste des taches d'installation/mise à jour d'une image Docker
#------------------------------------------------------------------------

# Connexion au repository Nexus/récupération de l'image/logout
- name: "Log into nexus repository"
  command: docker login {{ nexus_repo }} -u {{ nexus_user }} -p {{ nexus_password }}
  no_log: true

- name: "Log out of any docker registry"
  command: docker logout {{ nexus_repo }}
  no_log: true

- name: "Install intégration"
  block:
      # Déploiement des fichiers de configuration de l'application
    - name: "Copy infra/deploiement"
      copy:
        src: ../infra/deployment/docker-compose.yml
        dest: "/home/d_dawar/docker-compose.yml"
        mode: 0755

    - name: "Copy Markefile"
      copy:
        src: ../infra/deployment/Makefile
        dest: "/home/d_dawar/Makefile"

    - name: "Creating new .env file"
      template:
        src: "../.gitlab-ci/templates/.env.j2"
        dest: "/home/d_dawar/.env"

    - name: "Creating new .data-warehouse file"
      template:
        src: "../.gitlab-ci/templates/.data-warehouse.j2"
        dest: "/home/d_dawar/.data-warehouse"

    - name: "Pull docker images"
      command: "docker pull {{ docker_image_path }}"
      args:
        chdir: "/home/d_dawar"
  when: env == "int"

- name: "Install Production"
  block:
      # Déploiement des fichiers de configuration de l'application
    - name: "Copy infra/deploiement"
      copy:
        src: ../infra/deployment/docker-compose.yml
        dest: "/opt/docker/datawarehouse/docker-compose.yml"
        mode: 0755

    - name: "Copy Markefile"
      copy:
        src: ../infra/deployment/Makefile
        dest: "/opt/docker/Makefile"

    - name: "Creating new .env file"
      template:
        src: "../.gitlab-ci/templates/.env.j2"
        dest: "/opt/docker/datawarehouse/.env"

    - name: "Creating new .data-warehouse file"
      template:
        src: "../.gitlab-ci/templates/.data-warehouse.j2"
        dest: "/opt/docker/datawarehouse/.data-warehouse"

    - name: "Pull docker images"
      command: "docker pull {{ docker_image_path }}"
      args:
        chdir: "/opt/docker/datawarehouse"
  when: env == "prod"