CREATE TABLE IF NOT EXISTS rapportnav.aem (
    id Int32,
    idUUID String,
    serviceId Int32,
    missionTypes Array(String),
    controlUnitsIds Array(Int32),
    facade String,
    annee Int32,
    1_1_1_nombre_d_heures_de_mer Int32,
    1_1_3_nombre_d_operations_conduites Int32,
    1_1_4_nombre_de_personnes_secourues Int32, 
    1_2_1_nombre_d_heures_de_mer Int32,
    1_2_3_nombre_d_operations_conduites Int32,
    1_2_4_sar_migrants_nombre_d_embarcations_suivies_sans_necessite_d_intervention Int32,
    1_2_5_sar_migrantsnombre_d_embarcations_assistees_pour_un_retour_a_terre Int32,
    1_2_6_sar_migrants_nombre_d_operations_de_sauvetage_conduites Int32,
    1_2_7_sar_migrantsnombre_de_personnes_secourues Int32,
    2_1_nombre_d_heures_de_mer Int32,
    2_3_nombre_d_operations_aned_mise_en_oeuvre_de_moyens_nautique_ou_aerien Int32,
    2_4_nombre_d_intervention_faisant_suite_a_une_mise_en_demeure Int32,
    2_7_nombre_de_remorquages Int32, 
    3_3_1_nombre_d_heures_de_mer Int32,
    3_3_3_nombre_de_navires_ou_embarcations_deroutes_ou_saisis_en_mer Int32,
    3_3_4_nombre_de_saisies Int32,
    4_1_1_nombre_d_heures_de_mer_de_surveillance_ou_de_controle_pour_la_protection_de_l_environnement_hors_rejets_illicites Int32,
    4_1_3_nombre_d_operations_de_surveillance_ou_de_controles_hors_rejets_illicites Int32,
    4_1_4_nombre_d_infractions_a_la_reglementation_relative_a_la_protection_de_l_environnement_en_mer_hors_rejets_illicites Int32,
    4_1_5_nombre_de_proces_verbaux_dresses_en_mer_hors_rejets_illicites Int32,
    4_2_1_nombre_d_heures_de_mer_surveillance_et_lutte Int32,
    4_2_3_participation_a_une_operation_de_lutte_antipol_en_mer_simple_brassage Int32,
    4_2_4_deploiement_d_un_dispositif_de_lutte_anti_pollution_en_mer_dispersant_barrage_etc Int32,
    4_2_5_nombre_d_infractions_constatees Int32,
    4_2_6_nombre_de_proces_verbaux_dresses Int32,
    4_2_7_nombre_de_deroutements_effectues Int32,
    4_2_8_nombre_de_pollutions_detectees_etou_constatees_par_un_agent_habilite Int32,
    4_3_1_nombre_d_heures_de_mer_surveillancepolice_des_peches Int32,
    4_3_3_nombre_d_operations_polpeche Int32,
    4_3_5_nombre_de_navires_inspectes_en_mer_montee_a_bord Int32,
    4_3_6_nombre_de_proces_verbaux_dresses_en_mer_legislation_peche Int32,
    4_3_7_nombre_d_infractions_constatees_en_mer Int32,
    4_3_8_nombre_de_navires_accompagnes_ou_deroutes Int32,
    4_3_9_quantite_de_produits_de_la_peche_saisisrejetes_en_meren_kg Int32,
    7_1_nombre_d_heures_de_mer_de_surveillance_generale_des_approches_maritimes_zee Int32,
    7_3_nombre_total_de_navires_reconnus_dans_les_approches_maritimes_zee Int32,
    7_4_nombre_de_controles_en_mer_de_navires_toutes_zones Int32,

)
ENGINE = MergeTree()
ORDER BY id