CREATE TABLE IF NOT EXISTS rapportnav.aem (
    id Int32,
    idUUID String,
    serviceId Int32,
    missionTypes Array(String),
    controlUnitsIds Array(Int32),
    facade String,
    annee Int32,
    mois Int32,
    1_1_1_nombre_d_heures_de_mer Int32,
    1_1_3_nombre_d_operations_conduites Int32,
    1_1_4_nombre_de_personnes_secourues Int32, 
    1_2_1_nombre_d_heures_de_mer Int32,
    1_2_3_nombre_d_operations_conduites Int32,
    1_2_4_sar_migrants_nombre_d_embarcations Int32,
    1_2_5_sar_migrantsnombre_d_embarcations_ Int32,
    1_2_6_sar_migrants_nombre_d_operations_d Int32,
    1_2_7_sar_migrantsnombre_de_personnes_se Int32,
    2_1_nombre_d_heures_de_mer Int32,
    2_3_nombre_d_operations_aned_mise_en_oeu Int32,
    2_4_nombre_d_intervention_faisant_suite_ Int32,
    2_7_nombre_de_remorquages Int32, 
    3_3_1_nombre_d_heures_de_mer Int32,
    3_3_3_nombre_de_navires_ou_embarcations_ Int32,
    3_3_4_nombre_de_saisies Int32,
    4_1_1_nombre_d_heures_de_mer_de_surveill Int32,
    4_1_3_nombre_d_operations_de_surveillanc Int32,
    4_1_4_nombre_d_infractions_a_la_reglemen Int32,
    4_1_5_nombre_de_proces_verbaux_dresses_e Int32,
    4_2_1_nombre_d_heures_de_mer_surveillanc Int32,
    4_2_3_participation_a_une_operation_de_l Int32,
    4_2_4_deploiement_d_un_dispositif_de_lut Int32,
    4_2_5_nombre_d_infractions_constatees Int32,
    4_2_6_nombre_de_proces_verbaux_dresses Int32,
    4_2_7_nombre_de_deroutements_effectues Int32,
    4_2_8_nombre_de_pollutions_detectees_eto Int32,
    4_3_1_nombre_d_heures_de_mer_surveillanc Int32,
    4_3_3_nombre_d_operations_polpeche Int32,
    4_3_5_nombre_de_navires_inspectes_en_mer Int32,
    4_3_6_nombre_de_proces_verbaux_dresses_e Int32,
    4_3_7_nombre_d_infractions_constatees_en Int32,
    4_3_8_nombre_de_navires_accompagnes_ou_d Int32,
    4_3_9_quantite_de_produits_de_la_peche_s Int32,
    7_1_nombre_d_heures_de_mer_de_surveillan Int32,
    7_3_nombre_total_de_navires_reconnus_dan Int32,
    7_4_nombre_de_controles_en_mer_de_navire Int32,

)
ENGINE = MergeTree()
ORDER BY id