name: "[Release] Mirror push to gitlab"

on:
  #  push:
  #    branches: [ "main" ]
  # release:
  #   types: [ published ]
  workflow_dispatch:

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror + trigger CI
        uses: yesolutions/mirror-action@master
        with:
          REMOTE: https://gitlab-sml.din.developpement-durable.gouv.fr/num3-exploitation/deploiement-continu/gitlab-ci/applications/monitorfish-datawarehouse.git
          GIT_USERNAME: ${{ github.actor }}
          GIT_PASSWORD: ${{ secrets.GITLAB_MIRROR_TOKEN }}
          GIT_PUSH_ARGS: "--tags --prune"
          PUSH_ALL_REFS: false
          DEBUG: true